/* Generated by Yosys 0.59+134 (git sha1 07a690570, clang++ 18.1.8 -fPIC -O3) */

module adder_half_gateflow(a, b, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  output sum;
  wire sum;
  output carry;
  wire carry;
  assign carry = a & b;
  assign sum = a ^ b;
endmodule
