/* Generated by Yosys 0.59+134 (git sha1 07a690570, clang++ 18.1.8 -fPIC -O3) */

module counter(clk, res_n, up_down, enable, load, set, count);
  input clk;
  wire clk;
  input res_n;
  wire res_n;
  input up_down;
  wire up_down;
  input enable;
  wire enable;
  input load;
  wire load;
  input [2:0] set;
  wire [2:0] set;
  output [2:0] count;
  reg [2:0] count;
  wire [2:0] _00_;
  wire _01_;
  wire [2:0] _02_;
  wire [2:0] _03_;
  wire [31:0] _04_;
  assign _00_ = count + _04_[2:0];
  always @(posedge clk)
    if (!res_n) count <= 3'h0;
    else if (_01_) count <= _03_;
  assign _01_ = | { load, enable };
  assign _02_ = enable ? _00_ : 3'hx;
  assign _03_ = load ? set : _02_;
  assign _04_[2:0] = up_down ? 3'h1 : 3'h7;
  assign _04_[31:3] = 29'hxxxxxxxx;
endmodule
