/* Generated by Yosys 0.59+134 (git sha1 07a690570, clang++ 18.1.8 -fPIC -O3) */

module counter_tff_async(clk, res_n, en, count);
  input clk;
  wire clk;
  input res_n;
  wire res_n;
  input en;
  wire en;
  output [2:0] count;
  wire [2:0] count;
  wire [2:0] ff_clk;
  assign ff_clk[1] = ~ count[0];
  assign ff_clk[2] = ~ count[1];
  ff_t ff_0 (
    .Q(count[0]),
    .T(en),
    .clk(clk),
    .res_n(res_n)
  );
  ff_t \genblk1[1].ff_i  (
    .Q(count[1]),
    .T(en),
    .clk(ff_clk[1]),
    .res_n(res_n)
  );
  ff_t \genblk1[2].ff_i  (
    .Q(count[2]),
    .T(en),
    .clk(ff_clk[2]),
    .res_n(res_n)
  );
  assign ff_clk[0] = clk;
endmodule

module ff_t(clk, res_n, T, Q);
  input clk;
  wire clk;
  input res_n;
  wire res_n;
  input T;
  wire T;
  output Q;
  reg Q;
  wire _0_;
  always @(posedge clk, negedge res_n)
    if (!res_n) Q <= 1'h0;
    else if (T) Q <= _0_;
  assign _0_ = ~ Q;
endmodule
