/* Generated by Yosys 0.59+134 (git sha1 07a690570, clang++ 18.1.8 -fPIC -O3) */

module counter_jkff(clk, res_n, en, count);
  input clk;
  wire clk;
  input res_n;
  wire res_n;
  input en;
  wire en;
  output [2:0] count;
  wire [2:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire j;
  wire k;
  assign _00_ = _04_ & res_n;
  assign _02_ = _06_ & res_n;
  assign _01_ = clk & _05_;
  assign j = en & res_n;
  assign _03_ = res_n & _07_;
  assign _04_ = ~ count[0];
  assign _06_ = ~ count[1];
  assign _05_ = ~ res_n;
  assign _07_ = ~ en;
  assign k = ~ _03_;
  assign _08_ = _00_ | _01_;
  assign _09_ = _02_ | _01_;
  ff_jk \genblk1[0].genblk1.ff_i  (
    .J(j),
    .K(k),
    .Q(count[0]),
    .clk(clk)
  );
  ff_jk \genblk1[1].genblk1.ff_i  (
    .J(j),
    .K(k),
    .Q(count[1]),
    .clk(_08_)
  );
  ff_jk \genblk1[2].genblk1.ff_i  (
    .J(j),
    .K(k),
    .Q(count[2]),
    .clk(_09_)
  );
endmodule

module ff_jk(clk, J, K, Q);
  input clk;
  wire clk;
  input J;
  wire J;
  input K;
  wire K;
  output Q;
  reg Q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  always @(posedge clk)
    if (!_05_) Q <= _00_;
  assign _01_ = ~ Q;
  function [0:0] _08_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _08_ = b[0:0];
      3'b?1?:
        _08_ = b[1:1];
      3'b1??:
        _08_ = b[2:2];
      default:
        _08_ = a;
    endcase
  endfunction
  assign _00_ = _08_(1'hx, { 2'h1, _01_ }, { _04_, _03_, _02_ });
  assign _02_ = { J, K } == 2'h3;
  assign _03_ = { J, K } == 2'h2;
  assign _04_ = { J, K } == 1'h1;
  assign _05_ = ! { J, K };
endmodule
