#ifndef COMMON_H
#include "common.h"
#endif
#include "sequencer.cpp"
#include "scoreboard.cpp"
#include "monitor.cpp"
#include "driver.cpp"

extern Logger *logger;
Scoreboard *scb = new Scoreboard();
Sequencer *sqr = new Sequencer();


class Environment {
public:
    Interface *inf;
    Driver *drv;
    Monitor *mon;
    int total_cmd;

    Environment(Interface *intef):
        total_cmd(0),
        inf(intef),
        mon(new Monitor(intef, scb)),
        drv(new Driver(intef))
    {}

    ~Environment() {
        delete mon;
        delete scb;
        delete sqr;
        delete drv;
    }

    /** Run all the sequences generated by test
    */
    void main(int abort_on_first_err = 1) {
        int phase_num = 0;
        total_cmd = sqr->sqr_fifo.size();   // zero commands are not in fifo
        printf("INFO: Starting main test: processing %d instructions\n", total_cmd);
        scb->pre_test();

        while (!sqr->sqr_fifo.empty()) {
            logger->start_log(phase_num);
            sqr->main();
            printf("INFO: finished building mem file %d with %d transactions out of %d. Current queue size: %ld\n",
                phase_num, sqr->cmd_count, total_cmd, sqr->sqr_fifo.size());

            inf->boot_load();
            inf->reset();

            if (run_phase()) {
                // phase failed: log output
                printf("INFO: Caused by last transaction:\n");
                inf->dump(1);
                printf("INFO: Peeking on the next transaction:\n");
                inf->wait(CLK_PHASE * 2);
                inf->dump(1);
                printf("INFO: Full log of current phase:\n");
                logger->print_log();

                // post phase:
                if (abort_on_first_err) {
                    printf("INFO: Aborting test and all its phases\n");
                    while (!sqr->sqr_fifo.empty()) sqr->sqr_fifo.pop();
                    break;
                } else if (!sqr->sqr_fifo.empty()) {
                    // continue to next test if previous failed: forward expected tx to next set
                    scb->forward_to_set(phase_num + 1);
                    drv->forward_to_set(phase_num + 1);
                }
            }
            printf("INFO: Finished verification phase %d\n\n", phase_num);
            phase_num++;
        }
        // check that all commands were executed
        // ignoring if went below 0 because of zero commands
        if (!scb->err_count && total_cmd > 0) {
            printf("ERROR: did not proccess %d commands. %ld commands remained in Sequencer.\n\n",
                total_cmd, sqr->sqr_fifo.size());
            scb->err_total++;
        }
        // check driver stimulus was applied
        if (!scb->err_count && !drv_fifo.empty()) {
            printf("ERROR: unsent %ld transactions by driver\n\n", drv_fifo.size());
            scb->err_total++;
        }
        // post test: prepare for next test
        scb->post_test();
        while (!drv_fifo.empty()) drv_fifo.pop();
        sqr->split_count = 0;
    }

    /** Run sequences in the Instructions ROM
    *
    * @return 0 on success, 1 on error
    */
    int run_phase() {
        int max_time = inf->timestamp + CLK_PHASE * 2 * (sqr->cmd_count + 1);
        printf("INFO: timestamp limit for this phase is %d \n", max_time);

        while (inf->timestamp < max_time) {
            drv->main();        // waits until hold time after posedge
            mon->main();        // waits until setup time before posedge

            if (scb->is_finished()) {
                printf("INFO: Scoreboard has no expected results, finishing phase\n");
                break;
            }
            if (scb->main()) {
                return 1;
            }
            total_cmd--;
        }
        return 0;
    }
};
