#ifndef COMMON_H
#include "common.h"
#endif
#include "sequencer.cpp"
#include "scoreboard.cpp"
#include "monitor.cpp"
#include "driver.cpp"

extern Logger *logger;
Scoreboard *scb = new Scoreboard();
Sequencer *sqr = new Sequencer();


class Environment {
public:
    Interface *inf;
    Driver *drv;
    Monitor *mon;

    Environment(Interface *intef):
        inf(intef),
        drv(new Driver(intef)),
        mon(new Monitor(intef, scb)) {}

    ~Environment() {
        delete mon;
        delete scb;
        delete drv;
        delete sqr;
    }

    /** Run all the sequences generated by test
    */
    void main(int abort_on_first_err = 1) {
        int phase_num = 0;
        int res_count;
        char memfile[40];
        printf("INFO: Starting main test: processing %ld instructions\n", sqr->size());
        scb->pre_test();

        while (sqr->size()) {
            logger->start_log(phase_num);
            sprintf(memfile, "%s.mem", logger->get_name());
            sqr->main(memfile);
            printf("INFO: Starting phase %d with %d transactions out of %ld\n",
                phase_num, sqr->cmd_count, sqr->size());

            inf->boot_load(memfile);
            inf->reset();
            res_count = scb->res_count;

            if (run_phase()) {
                // phase failed: log output
                printf("INFO: Caused by last transaction:\n");
                inf->dump(1);
                inf->dump_regfile();
                printf("INFO: Peeking on the next transaction:\n");
                inf->wait(CLK_PHASE * 2);
                inf->dump(1);
                printf("INFO: Full log of current phase:\n");
                logger->print_log();

                // post phase:
                if (abort_on_first_err) {
                    printf("WARNING: Aborting test and all its phases\n");
                    sqr->reset();
                    break;
                } else if (sqr->size()) {
                    // continue to next test if previous failed: forward expected tx to next phase num
                    scb->post_phase(phase_num + 1);
                    drv->post_phase(phase_num + 1);
                }
            }
            // phase post checks:
            if (!scb->err_count && sqr->cmd_count > 0) {
                printf("WARNING: did not process %d commands\n\n", sqr->cmd_count);
            }
            printf("INFO: Finished verification phase %d of %s\n\n", phase_num, memfile);
            phase_num++;
        }
        // test post checks:
        // check driver stimulus was applied
        if (!scb->err_count && !drv_fifo.empty()) {
            printf("ERROR: unsent %ld transactions by driver\n\n", drv_fifo.size());
            scb->err_total++;
        }
        post_test();
    }

    /** Run sequences in the Instructions ROM
     *
     * @return 0 on success, 1 on error
     */
    int run_phase() {
        unsigned long max_time = inf->timestamp + CLK_PHASE * 2 * (sqr->cmd_count + 3);
        printf("INFO: timestamp limit for this phase is %ld\n", max_time);

        while (inf->timestamp < max_time) {
            drv->main();                // waits until hold time after posedge
            mon->main();                // waits until setup time before posedge
            if (scb->main()) {          // aborting phase on error
                return 1;
            }
            if (inf->stop_event()) {
                printf("INFO: Phase finished on interface stop condition\n");
                break;
            }
            if (!sqr->cmd_count) {  //  || sqr->cmd_count == INSTRUCTIONS_LIMIT
                printf("INFO: Phase finished on commands counter exhaustion\n");
                break;
            }
            sqr->cmd_count--;
        }
        if (inf->timestamp >= max_time) {
            printf("INFO: Phase finished on timeout\n");
        }
        return 0;
    }

    /** post test: prepare for next test
     * 
    */
    void post_test() {
        scb->post_test();
        sqr->post_test();
        drv->post_test();
    }
};
