#ifndef COMMON_H
#include "common.h"
#endif
#include "sequencer.cpp"
#include "scoreboard.cpp"
#include "monitor.cpp"
#include "driver.cpp"
Scoreboard *scb = new Scoreboard();
Sequencer *sqr = new Sequencer();



class Environment {
public:
    Interface *inf;
    Monitor *mon;
    Driver *drv;
    int total_cmd;

    Environment(Interface *intef):
        total_cmd(0),
        inf(intef),
        mon(new Monitor(intef, scb)),
        drv(new Driver(intef))
    {}

    ~Environment() {
        delete mon;
        delete scb;
        delete sqr;
        delete drv;
    }

    /* Run all the sequences generated by test
    */
    void main() {
        int phase_num = 0;
        total_cmd = sqr->sqr_fifo.size();   // zero commands are not in fifo
        scb->pre_test();
        printf("INFO: Starting main test: processing %d instructions\n", total_cmd);

        while (!sqr->sqr_fifo.empty()) {
            sqr->main();
            printf("INFO: finished building mem file %d with %d transactions out of %d. Current queue size: %ld\n",
                phase_num, sqr->cmd_count, total_cmd, sqr->sqr_fifo.size());

            inf->boot_load();
            inf->reset();

            if (run_phase()) {
                // continue to next test if previous failed: forward expected tx to next set
                if (!sqr->sqr_fifo.empty()) {
                    scb->forward_to_set(phase_num + 1);
                }
            }
            printf("INFO: Finished verification phase %d\n\n", phase_num);
            phase_num++;
        }

        if (!scb->err_count && total_cmd > 0) {    // ignoring if went below 0 because of zero commands
            printf("ERROR: did not proccess %d commands. %ld commands remained in Sequencer.\n\n",
                total_cmd, sqr->sqr_fifo.size());
            scb->err_total++;
        }
        // post test phase prepare for next test
        scb->post_test();
        sqr->split_count = 0;
    }

    /* Run only the sequences which were loaded into Instructions ROM
    *
    * return: 0 on success, 1 on error
    */
    int run_phase() {
        int max_sim_time = inf->timestamp + CLK_PHASE * 2 * (sqr->cmd_count + 1);
        printf("INFO: timestamp limit for this phase is %d \n", max_sim_time);

        while (inf->timestamp < max_sim_time) {
            drv->main();    // waits until hold time after posedge
            mon->main();    // waits until setup time before posedge

            if (scb->is_finished()) {
                printf("INFO: Scoreboard has no expected results, finishing phase\n");
                break;
            }
            if (scb->main()) {
                printf("INFO: Caused by last transaction:\n");
                inf->dump(1);
                printf("INFO: Peeking on the next transaction:\n");
                inf->wait(CLK_PHASE * 2);
                inf->dump(1);
                return 1;
            }
            // wait until posedge (this wait can be moved into the end of monitor main)
            //inf->wait(CLK_PHASE - inf->timestamp % CLK_PHASE);
            total_cmd--;
        }
        return 0;
    }
};
