name: Verilog CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/configure-pages@v5
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          curl -L https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2026-04-19/oss-cad-suite-linux-x64-20260419.tgz -o oss.tgz
          wget https://www.accellera.org/images/downloads/standards/uvm/uvm-1.2.tar.gz
          mkdir -p $HOME/dev/sda6/oss-cad-suite/
          mkdir -p $HOME/dev/sda6/UVM/UVM1.2/
          tar -xzf oss.tgz -C $HOME/dev/sda6/
          tar -xzf uvm-1.2.tar.gz -C $HOME/dev/sda6/UVM/UVM1.2/ --strip-components=1
          ls $HOME/dev/sda6
          ls $HOME/dev/sda6/UVM/UVM1.2/src

      - name: Regression with GATE_FLOW OFF (iverilog)
        run: make all ARG="-DGATE_FLOW_OFF" 2>&1 | tee dataflow.log

      - name: Regression with GATE_FLOW ON (iverilog)
        run: make all 2>&1 | tee gateflow.log

      - name: Modules regression (verilator)
        run: make regression SIM=v RM_OBJDIR=true 2>&1 | tee modules.log

      - name: UART C++ and verilog tests (verilator)
        run: make uart SIM=v RM_OBJDIR=true 2>&1 | tee uart.log

      - name: RISCV tests (verilator)
        run: make risc SIM=v RM_OBJDIR=true 2>&1 | tee riscv.log

      - name: ALU SystemVerilog testbench (verilator)
        run: make alu ARG=-UDEBUG_RUN RM_OBJDIR=true 2>&1 | tee alusv.log

      - name: FIFO UVM testbench (verilator)
        run: make uvm-fifo 2>&1 | tee fifouvm.log

      - name: Grep Results Summary
        run: make grep_err

      - name: Get coverage report
        run: make get_coverage || cat coverage_merged_notb.dat

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./covhtml

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
